# Generated by Django 5.2.7 on 2025-11-07 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, help_text="Dat lich ngay", max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Biển số xe"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Hãng xe")),
                ("model", models.CharField(max_length=100, verbose_name="loai xe")),
                ("year", models.IntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chu xe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("confirmed", "Đã xác nhận"),
                            ("in_progress", "Đang sửa chữa"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trang thai",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khach hang",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="first_app.car",
                        verbose_name="xe",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        to="first_app.services",
                        verbose_name="Dich vu cham soc khach hang",
                    ),
                ),
            ],
        ),
    ]
