# Generated by Django 5.2.7 on 2025-11-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="Message",
            new_name="message",
        ),
    ]
