# Generated by Django 5.2.7 on 2025-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_rename_message_contact_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="autoParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Loai Phu Tung",
                "verbose_name_plural": "Cac Loai Phu Tung",
            },
        ),
    ]
