# Generated by Django 5.2.7 on 2025-11-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0004_autoparts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="autoParts",
            new_name="PartCategory",
        ),
    ]
