# Generated by Django 5.2.7 on 2025-11-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_rename_autoparts_partcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên Phụ Tùng")),
                (
                    "part_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Mã SP"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Thương hiệu",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Số lượng")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Giá",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="parts_images/",
                        verbose_name="Ảnh",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.partcategory",
                        verbose_name="Loại Phụ Tùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phụ Tùng",
                "verbose_name_plural": "Các Phụ Tùng",
            },
        ),
    ]
