# Generated by Django 5.2.7 on 2025-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0007_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
