# Generated by Django 5.2.7 on 2025-11-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0008_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="partcategory",
            options={
                "verbose_name": "Loại Phụ Tùng",
                "verbose_name_plural": "Các Loại Phụ Tùng",
            },
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tên Loại Phụ Tùng"),
        ),
        migrations.AddField(
            model_name="partcategory",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="first_app.partgroup",
                verbose_name="Thuộc Nhóm",
            ),
        ),
    ]
