# Generated by Django 5.2.7 on 2025-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0009_partgroup_alter_partcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="image",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Link Ảnh"
            ),
        ),
    ]
