"""
Django settings for first_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hwk2zj6rxf940#l*e4)#(tit8$noq!    rlvq)4-vhasqd#h)2bf^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['hoangkimbao1505.pythonanywhere.com','127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "first_app"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "first_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                "first_app.context_processors.global_services_list",
                "first_app.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "first_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Báo cho Django biết trang login của chúng ta ở đâu
# Sau khi đăng nhập thành công -> Về trang chủ (có name='index')
LOGIN_REDIRECT_URL = 'index'

# Sau khi đăng xuất -> Cũng về trang chủ
LOGOUT_REDIRECT_URL = 'index'

# Đường dẫn trang login (để Django biết khi cần bắt đăng nhập)
LOGIN_URL = 'login'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kimbao10c4@gmail.com'  # ⬅️ Điền email của bạn
EMAIL_HOST_PASSWORD = 'idaf sczu ustl mlmi' # ⬅️ Điền mật khẩu ứng dụng (App Password)

CART_SESSION_ID = 'cart'

# VNPAY CONFIGURATION
VNPAY_TMN_CODE = '8EF1ZQQA'  # Thay bằng TmnCode của bạn
VNPAY_HASH_SECRET_KEY = 'D3MLK142M2G9V1QNWNJB8TUE1FQPAH6C'  # Thay bằng Hash Secret của bạn
VNPAY_PAYMENT_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'  # URL thanh toán của VNPay
VNPAY_RETURN_URL = 'http://127.0.0.1:8000/payment/return/' # URL trả về sau khi thanh toán
VNPAY_IPN_URL = 'http://127.0.0.1:8000/payment/ipn/' # URL IPN của VNPay


